const MaastrichtBlue = "#0B1933";
const BlueYonder = "#466DB5";
const Pear = "#C5D92D";
const RichBlack = "#001022";
const AntiFlashWhite = "#F2F3F5";

export const Colors = {
  primary: MaastrichtBlue,
  secondary: BlueYonder,
  accent: Pear,
  background: AntiFlashWhite,
  surface: "#FFFFFF",
  surfaceElevated: "#FFFFFF",
  border: "#E2E5EC",
  borderLight: "#EDF0F5",
  text: RichBlack,
  textSecondary: "#566077",
  textTertiary: "#8A96AA",
  textOnDark: "#FFFFFF",
  textOnAccent: MaastrichtBlue,
  cardBackground: "#FFFFFF",
  tabBar: MaastrichtBlue,
  tabBarActive: Pear,
  tabBarInactive: "#8A96AA",
  danger: "#E53E3E",
  dangerLight: "#FFF5F5",
  dangerBorder: "#FEB2B2",
  warning: "#DD6B20",
  warningLight: "#FFFAF0",
  warningBorder: "#FBD38D",
  success: "#2F855A",
  successLight: "#F0FFF4",
  successBorder: "#9AE6B4",
  info: BlueYonder,
  infoLight: "#EBF1FB",
  infoBorder: "#BFD0EE",
  severity: {
    critical: "#E53E3E",
    criticalBg: "#FFF5F5",
    high: "#DD6B20",
    highBg: "#FFFAF0",
    medium: "#D69E2E",
    mediumBg: "#FFFFF0",
    low: "#2F855A",
    lowBg: "#F0FFF4",
  },
  status: {
    active: "#2F855A",
    activeBg: "#F0FFF4",
    on_hold: "#D69E2E",
    on_holdBg: "#FFFFF0",
    completed: BlueYonder,
    completedBg: "#EBF1FB",
    archived: "#718096",
    archivedBg: "#F7FAFC",
    scheduled: BlueYonder,
    scheduledBg: "#EBF1FB",
    in_progress: "#D69E2E",
    in_progressBg: "#FFFFF0",
    follow_up_required: "#E53E3E",
    follow_up_requiredBg: "#FFF5F5",
    cancelled: "#718096",
    cancelledBg: "#F7FAFC",
    open: "#E53E3E",
    openBg: "#FFF5F5",
    in_progress2: "#D69E2E",
    resolved: "#2F855A",
    resolvedBg: "#F0FFF4",
    closed: "#718096",
    closedBg: "#F7FAFC",
    deferred: "#9F7AEA",
    deferredBg: "#FAF5FF",
  },
  shadow: "rgba(11, 25, 51, 0.08)",
  overlay: "rgba(0, 16, 34, 0.6)",
};

export default Colors;
