import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import projectsRouter from "./projects";
import inspectionsRouter from "./inspections";
import checklistsRouter from "./checklists";
import issuesRouter from "./issues";
import documentsRouter from "./documents";
import notesRouter from "./notes";
import reportsRouter from "./reports";
import analyticsRouter from "./analytics";
import notificationsRouter from "./notifications";
import usersRouter from "./users";
import storageRouter from "./storage";
import billingRouter from "./billing";
import adminRouter from "./admin";
import invitesRouter from "./invites";
import docTemplatesRouter from "./docTemplates";
import feedbackRouter from "./feedback";
import markupRouter from "./markup";
import internalStaffRouter from "./internalStaff";
import orgContractorsRouter from "./orgContractors";
import activityRouter from "./activity";
import shareRouter from "./share";
import inductionsRouter from "./inductions";
import internalRouter from "./internal";
import calendarIntegrationsRouter from "./calendarIntegrations";
import geocodeRouter from "./geocode";
import newslettersRouter from "./newsletters";
import orgsRouter from "./orgs";
import waitlistRouter from "./waitlist";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/projects", projectsRouter);
router.use("/inspections", inspectionsRouter);
router.use("/checklist-templates", checklistsRouter);
router.use("/issues", issuesRouter);
router.use("/documents", documentsRouter);
router.use("/notes", notesRouter);
router.use("/reports", reportsRouter);
router.use("/analytics", analyticsRouter);
router.use("/notifications", notificationsRouter);
router.use("/users", usersRouter);
router.use(storageRouter);
router.use(billingRouter);
router.use(adminRouter);
router.use("/invites", invitesRouter);
router.use("/doc-templates", docTemplatesRouter);
router.use("/feedback", feedbackRouter);
router.use(markupRouter);
router.use("/internal-staff", internalStaffRouter);
router.use("/org-contractors", orgContractorsRouter);
router.use("/activity", activityRouter);
router.use(shareRouter);
router.use(inductionsRouter);
router.use(internalRouter);
router.use(calendarIntegrationsRouter);
router.use(geocodeRouter);
router.use(newslettersRouter);
router.use(orgsRouter);
router.use(waitlistRouter);

export default router;
