import { db } from "../index";
import { checklistTemplatesTable, checklistItemsTable } from "../schema/checklists";

type BSTemplateItem = {
  category: string;
  description: string;
  codeReference?: string | null;
  riskLevel: "low" | "medium" | "high" | "critical";
  isRequired: boolean;
  requirePhoto: boolean;
  defectTrigger: boolean;
  recommendedAction?: string | null;
  includeInReport: boolean;
};

type BSTemplate = {
  name: string;
  inspectionType: string;
  folder: string;
  description: string;
  sortOrder: number;
  items: BSTemplateItem[];
};

// ---------------------------------------------------------------------------
// Dwelling 1 Storey (Class 1) — NCC Housing Provisions
// ---------------------------------------------------------------------------

const DWELLING_1_STOREY: BSTemplate[] = [
  {
    name: "Footing Inspection",
    inspectionType: "footing",
    folder: "Dwelling 1 Storey (Class 1)",
    description: "Footing inspection prior to concrete pour — NCC Housing Provisions HP2.2",
    sortOrder: 1,
    items: [
      {
        category: "Excavation",
        description: "Footing depths comply with approved drawings and geotechnical requirements",
        codeReference: "NCC HP2.2",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: true,
        defectTrigger: true,
        recommendedAction: "Excavate to required depth and confirm with engineer before proceeding",
        includeInReport: true,
      },
      {
        category: "Excavation",
        description: "Natural undisturbed ground confirmed — no soft spots, fill or expansive clay present",
        codeReference: "NCC HP2.2",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        recommendedAction: "Notify engineer if fill or reactive soil encountered",
        includeInReport: true,
      },
      {
        category: "Reinforcement",
        description: "Rebar size, spacing and concrete cover comply with structural drawings per AS 3600",
        codeReference: "NCC HP2.3 / AS 3600",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: true,
        defectTrigger: true,
        recommendedAction: "Rectify reinforcement layout before pour",
        includeInReport: true,
      },
      {
        category: "Reinforcement",
        description: "Reinforcement laps, hooks and ties are correctly installed",
        codeReference: "AS 3600",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Reinforcement",
        description: "Starter bars for slab, piers or columns correctly positioned and tied",
        codeReference: "NCC HP2.3",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Services",
        description: "All service conduits and sleeves positioned and secured prior to pour",
        codeReference: null,
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Pre-Pour",
        description: "Formwork is structurally adequate, level and correctly aligned",
        codeReference: "NCC HP2.2",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Pre-Pour",
        description: "Termite management documentation provided or chemical barrier applied prior to pour",
        codeReference: "NCC HP4.5",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        recommendedAction: "Obtain termite treatment certificate before pour proceeds",
        includeInReport: true,
      },
    ],
  },
  {
    name: "Slab Inspection",
    inspectionType: "slab",
    folder: "Dwelling 1 Storey (Class 1)",
    description: "Slab inspection prior to concrete pour — NCC Housing Provisions HP3.2",
    sortOrder: 2,
    items: [
      {
        category: "Subbase",
        description: "Sand or gravel blinding layer installed to correct depth and level",
        codeReference: "NCC HP3.2",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Subbase",
        description: "Vapour barrier (minimum 0.2 mm polyethylene) installed with lapped and sealed joints",
        codeReference: "NCC HP3.2",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        recommendedAction: "Ensure all laps are minimum 200 mm and taped",
        includeInReport: true,
      },
      {
        category: "Subbase",
        description: "Perimeter edge form set to correct level — slab thickness verified against drawings",
        codeReference: "NCC HP3.2",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Reinforcement",
        description: "Mesh size, layout and bar chairs comply with structural drawings",
        codeReference: "AS 3600",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: true,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Reinforcement",
        description: "Edge beam reinforcement size and depth correct per structural specification",
        codeReference: "NCC HP3.2",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Services",
        description: "All conduit, pipes and floor wastes fixed in position and sleeved prior to pour",
        codeReference: null,
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Termite",
        description: "Ant caps or physical termite barrier installed to all penetrations through slab",
        codeReference: "NCC HP4.5",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        recommendedAction: "Install ant caps to all pipe and column penetrations before pour",
        includeInReport: true,
      },
      {
        category: "Pre-Pour",
        description: "Concrete mix design (MPa, slump, aggregate size) confirmed against specification",
        codeReference: "AS 1379",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Frame Inspection",
    inspectionType: "frame",
    folder: "Dwelling 1 Storey (Class 1)",
    description: "Timber frame inspection — NCC Housing Provisions HP3.4 / AS 1684",
    sortOrder: 3,
    items: [
      {
        category: "Wall Framing",
        description: "Stud size, spacing and stress grade comply with AS 1684 and HP3.4.2",
        codeReference: "NCC HP3.4.2 / AS 1684",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Wall Framing",
        description: "Bottom plates correctly fixed to slab — bolts or nail plates at required centres",
        codeReference: "NCC HP3.4.2",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Wall Framing",
        description: "Top plates doubled and correctly lapped at corners and junctions",
        codeReference: "AS 1684",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Bracing",
        description: "Bracing type, location and length verified against engineer's bracing schedule",
        codeReference: "NCC HP3.4.4",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        recommendedAction: "Do not proceed until bracing complies with schedule",
        includeInReport: true,
      },
      {
        category: "Bracing",
        description: "Bracing fixings and hold-down anchors installed per specification",
        codeReference: "NCC HP3.4.4",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Lintels",
        description: "Lintel sizes over all door and window openings comply with span tables",
        codeReference: "AS 1684",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Roof Framing",
        description: "Roof members (rafters, ridgeboard, hips, valleys) comply with HP3.4.3",
        codeReference: "NCC HP3.4.3",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Roof Framing",
        description: "Ceiling joists, collar ties and hanging beams comply with span tables",
        codeReference: "AS 1684",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Tie-Down",
        description: "Wind tie-down straps or connectors installed at required intervals per engineer",
        codeReference: "NCC HP3.4.4",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Penetrations",
        description: "Notching and drilling of framing members within allowable limits per AS 1684",
        codeReference: "AS 1684",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Waterproofing Inspection",
    inspectionType: "waterproofing",
    folder: "Dwelling 1 Storey (Class 1)",
    description: "Waterproofing and weather-resistance inspection — NCC Housing Provisions HP3.2.3 / HP3.3",
    sortOrder: 4,
    items: [
      {
        category: "Wet Areas",
        description: "Waterproofing membrane applied to all shower and wet area floors per HP3.2.3",
        codeReference: "NCC HP3.2.3 / AS 3740",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: true,
        defectTrigger: true,
        recommendedAction: "Apply compliant membrane and allow full cure time before tiling",
        includeInReport: true,
      },
      {
        category: "Wet Areas",
        description: "Membrane extends minimum 1800 mm up shower walls and 150 mm up bath surround walls",
        codeReference: "NCC HP3.2.3 / AS 3740",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Wet Areas",
        description: "Floor-wall junctions fully sealed with flexible sealant prior to tiling",
        codeReference: "AS 3740",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Wet Areas",
        description: "Membrane is continuous — no gaps, tears, bubbles or bridging over joints",
        codeReference: "AS 3740",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Roof",
        description: "Sarking (reflective foil laminate or vapour permeable membrane) installed under roof cladding",
        codeReference: "NCC HP3.3.1",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Roof",
        description: "Flashing installed at ridge, valleys, abutments and all roof penetrations",
        codeReference: "NCC HP3.3",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "External",
        description: "Window and door sill, head and jamb flashings correctly installed",
        codeReference: "NCC HP3.3",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "External",
        description: "Damp-proof course (DPC) installed at or above finished ground level",
        codeReference: "NCC HP3.4.1",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Fire Penetration Inspection",
    inspectionType: "fire_penetration",
    folder: "Dwelling 1 Storey (Class 1)",
    description: "Fire penetration and cavity barrier inspection — NCC Housing Provisions HP3.7 / DP2",
    sortOrder: 5,
    items: [
      {
        category: "Penetrations",
        description: "All service penetrations through fire-rated walls and floors identified and documented",
        codeReference: "NCC HP3.7",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Penetrations",
        description: "Fire-stopping compound, collars or wraps installed around all pipes and cables through fire-rated elements",
        codeReference: "NCC HP3.7 / Spec C3.15",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: true,
        defectTrigger: true,
        recommendedAction: "Install certified fire-stopping system and provide product documentation",
        includeInReport: true,
      },
      {
        category: "Penetrations",
        description: "Intumescent collars installed on all combustible pipes passing through fire-rated elements",
        codeReference: "NCC HP3.7",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Penetrations",
        description: "Electrical conduit penetrations through top and bottom plates sealed",
        codeReference: "NCC DP2",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Cavity Barriers",
        description: "Cavity barriers installed in external wall cavities at required locations",
        codeReference: "NCC HP3.7",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Documentation",
        description: "Product documentation (ABCB CodeMark or AWA) for fire-rated construction systems available on site",
        codeReference: "NCC HP3.7",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Occupancy Inspection",
    inspectionType: "occupancy",
    folder: "Dwelling 1 Storey (Class 1)",
    description: "Pre-occupancy inspection — NCC Housing Provisions HP4 / EP2.2",
    sortOrder: 6,
    items: [
      {
        category: "Structure",
        description: "All structural elements complete and consistent with approved drawings",
        codeReference: "NCC HP",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Roof & Walls",
        description: "Roof covering complete, weather-tight and all penetrations flashed",
        codeReference: "NCC HP3.3",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Openings",
        description: "All external doors, windows and glazing installed correctly and weather-stripped",
        codeReference: "NCC HP3.3",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Stairs & Balustrades",
        description: "Stair riser and going dimensions, handrails and balustrades comply with HP3.9.2",
        codeReference: "NCC HP3.9.2",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Smoke Alarms",
        description: "Smoke alarms installed in all required locations per EP2.2 (each storey, each bedroom level)",
        codeReference: "NCC EP2.2",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        recommendedAction: "Install alarms in all required positions before occupancy",
        includeInReport: true,
      },
      {
        category: "Smoke Alarms",
        description: "Alarms are interconnected and hardwired, or 10-year lithium battery type as required",
        codeReference: "NCC EP2.2 / AS 3786",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Services",
        description: "Plumbing rough-in complete and hydraulic pressure test passed",
        codeReference: "AS/NZS 3500",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Energy",
        description: "Insulation installed per NatHERS certificate or DtS energy efficiency requirements",
        codeReference: "NCC HP6",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Final Inspection",
    inspectionType: "final",
    folder: "Dwelling 1 Storey (Class 1)",
    description: "Final inspection for occupation certificate — NCC Housing Provisions",
    sortOrder: 7,
    items: [
      {
        category: "Compliance",
        description: "All staged inspection approvals received and documented on file",
        codeReference: "NCC HP",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        recommendedAction: "Obtain all outstanding inspection sign-offs before issuing occupation certificate",
        includeInReport: true,
      },
      {
        category: "Site",
        description: "Site drainage, surface water management and subsoil drainage compliant",
        codeReference: "NCC HP2.1",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Compliance",
        description: "Building complete in accordance with all approved plans and specifications",
        codeReference: "NCC HP",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Safety Glazing",
        description: "Safety glazing installed in all hazardous locations per FP7.4",
        codeReference: "NCC FP7.4 / AS 1288",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Balustrades",
        description: "All balustrade heights (min 1000 mm) and infill spacings comply with HP3.9.2",
        codeReference: "NCC HP3.9.2",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Smoke Alarms",
        description: "All smoke alarms tested and operational",
        codeReference: "NCC EP2.2",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Energy",
        description: "Energy efficiency compliance documentation provided (NatHERS certificate or DtS path)",
        codeReference: "NCC HP6",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Termite",
        description: "Termite management system documentation and product warranty provided to owner",
        codeReference: "NCC HP4.5",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Certification",
        description: "All required certificates and authorities' sign-offs received",
        codeReference: null,
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Certification",
        description: "Owner provided with maintenance manual or as-built documentation",
        codeReference: null,
        riskLevel: "low",
        isRequired: false,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// Dwelling 2 Storey (Class 1) — NCC Housing Provisions
// ---------------------------------------------------------------------------

const DWELLING_2_STOREY: BSTemplate[] = [
  {
    name: "Footing Inspection",
    inspectionType: "footing",
    folder: "Dwelling 2 Storey (Class 1)",
    description: "Footing inspection for two-storey dwelling prior to concrete pour — NCC Housing Provisions HP2.2",
    sortOrder: 1,
    items: [
      {
        category: "Excavation",
        description: "Footing depths and dimensions comply with engineer's design — sized for two-storey loading",
        codeReference: "NCC HP2.2",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: true,
        defectTrigger: true,
        recommendedAction: "Excavate to required depth per engineer's drawings before pour",
        includeInReport: true,
      },
      {
        category: "Excavation",
        description: "Natural undisturbed ground confirmed — no soft spots, fill or expansive clay",
        codeReference: "NCC HP2.2",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        recommendedAction: "Notify structural engineer if unexpected soil conditions found",
        includeInReport: true,
      },
      {
        category: "Reinforcement",
        description: "Rebar size, spacing and cover comply with structural drawings for two-storey loads (AS 3600)",
        codeReference: "NCC HP2.3 / AS 3600",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: true,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Reinforcement",
        description: "Reinforcement laps, hooks and ties correctly installed",
        codeReference: "AS 3600",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Reinforcement",
        description: "Starter bars for columns and walls correctly positioned and tied at required height",
        codeReference: "NCC HP2.3",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Services",
        description: "All service conduits and sleeves positioned and secured prior to pour",
        codeReference: null,
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Pre-Pour",
        description: "Formwork structurally adequate, level and correctly aligned",
        codeReference: "NCC HP2.2",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Pre-Pour",
        description: "Termite management documentation provided or chemical barrier applied prior to pour",
        codeReference: "NCC HP4.5",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        recommendedAction: "Obtain termite treatment certificate before pour proceeds",
        includeInReport: true,
      },
    ],
  },
  {
    name: "Slab Inspection",
    inspectionType: "slab",
    folder: "Dwelling 2 Storey (Class 1)",
    description: "Slab inspection prior to concrete pour — NCC Housing Provisions HP3.2",
    sortOrder: 2,
    items: [
      {
        category: "Subbase",
        description: "Sand or gravel blinding layer installed to correct depth and level",
        codeReference: "NCC HP3.2",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Subbase",
        description: "Vapour barrier (minimum 0.2 mm polyethylene) installed with lapped and sealed joints",
        codeReference: "NCC HP3.2",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Subbase",
        description: "Perimeter edge form set to correct level — slab thickness verified against drawings",
        codeReference: "NCC HP3.2",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Reinforcement",
        description: "Mesh size, layout and bar chairs comply with structural drawings — sized for two-storey",
        codeReference: "AS 3600",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: true,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Reinforcement",
        description: "Edge beam reinforcement size and depth correct per structural specification",
        codeReference: "NCC HP3.2",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Services",
        description: "All conduit, pipes and floor wastes fixed in position and sleeved prior to pour",
        codeReference: null,
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Termite",
        description: "Ant caps or physical termite barrier installed to all penetrations through slab",
        codeReference: "NCC HP4.5",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Pre-Pour",
        description: "Concrete mix design confirmed against specification — upper floor load path reviewed",
        codeReference: "AS 1379",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Frame Inspection",
    inspectionType: "frame",
    folder: "Dwelling 2 Storey (Class 1)",
    description: "Timber frame inspection for two-storey dwelling — NCC Housing Provisions HP3.4 / AS 1684",
    sortOrder: 3,
    items: [
      {
        category: "Ground Floor Framing",
        description: "Ground floor stud size and spacing designed for two-storey loading per AS 1684",
        codeReference: "NCC HP3.4.2 / AS 1684",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Ground Floor Framing",
        description: "Bottom plates correctly fixed to slab at required centres",
        codeReference: "NCC HP3.4.2",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Ground Floor Framing",
        description: "Top plates doubled and correctly lapped at all corners and junctions",
        codeReference: "AS 1684",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Upper Floor Structure",
        description: "First floor bearer and joist sizes comply with span tables for two-storey loading",
        codeReference: "AS 1684",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Upper Floor Structure",
        description: "Inter-floor connections (joist hangers, column caps, strap ties) installed per specification",
        codeReference: "AS 1684",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: true,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Upper Floor Framing",
        description: "Upper floor wall framing stud size and spacing per AS 1684",
        codeReference: "NCC HP3.4.2 / AS 1684",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Bracing",
        description: "Bracing schedule verified for both floors — racking loads distributed correctly at each level",
        codeReference: "NCC HP3.4.4",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        recommendedAction: "Do not proceed until bracing is installed per schedule for both levels",
        includeInReport: true,
      },
      {
        category: "Bracing",
        description: "Hold-down connections between floors and at base slab per engineer's specification",
        codeReference: "NCC HP3.4.4",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Lintels",
        description: "Lintel sizes over all openings at both levels account for upper floor loading",
        codeReference: "AS 1684",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Roof Framing",
        description: "Roof members (rafters, ridgeboard, hips, valleys) comply with HP3.4.3",
        codeReference: "NCC HP3.4.3",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Tie-Down",
        description: "Wind tie-down straps at all levels — roof to upper wall and upper wall to lower wall",
        codeReference: "NCC HP3.4.4",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Penetrations",
        description: "Notching and drilling of framing members within allowable limits at both levels",
        codeReference: "AS 1684",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Waterproofing Inspection",
    inspectionType: "waterproofing",
    folder: "Dwelling 2 Storey (Class 1)",
    description: "Waterproofing and weather-resistance inspection — NCC Housing Provisions HP3.2.3 / HP3.3",
    sortOrder: 4,
    items: [
      {
        category: "Wet Areas",
        description: "Waterproofing membrane applied to all shower and wet area floors per HP3.2.3",
        codeReference: "NCC HP3.2.3 / AS 3740",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: true,
        defectTrigger: true,
        recommendedAction: "Apply compliant membrane and allow full cure before tiling",
        includeInReport: true,
      },
      {
        category: "Wet Areas",
        description: "Membrane extends minimum 1800 mm up shower walls and 150 mm up bath surround walls",
        codeReference: "NCC HP3.2.3 / AS 3740",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Wet Areas",
        description: "Upper floor wet area waterproofing designed to prevent leakage to lower floor",
        codeReference: "NCC HP3.2.3",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        recommendedAction: "Verify grading and membrane coverage prevent any water penetration to storey below",
        includeInReport: true,
      },
      {
        category: "Wet Areas",
        description: "Floor-wall junctions fully sealed with flexible sealant — membrane continuous, no tears or gaps",
        codeReference: "AS 3740",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Roof",
        description: "Sarking installed under roof cladding per HP3.3.1",
        codeReference: "NCC HP3.3.1",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Roof",
        description: "Flashing installed at ridge, valleys, abutments and all roof penetrations",
        codeReference: "NCC HP3.3",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "External",
        description: "Window and door sill, head and jamb flashings installed at both levels",
        codeReference: "NCC HP3.3",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "External",
        description: "Damp-proof course (DPC) installed at or above finished ground level",
        codeReference: "NCC HP3.4.1",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Fire Penetration Inspection",
    inspectionType: "fire_penetration",
    folder: "Dwelling 2 Storey (Class 1)",
    description: "Fire penetration and cavity barrier inspection — NCC Housing Provisions HP3.7 / DP2",
    sortOrder: 5,
    items: [
      {
        category: "Penetrations",
        description: "All service penetrations through fire-rated walls and floors at both levels identified",
        codeReference: "NCC HP3.7",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Penetrations",
        description: "Fire-stopping compound, collars or wraps installed around all pipes and cables through fire-rated elements",
        codeReference: "NCC HP3.7 / Spec C3.15",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: true,
        defectTrigger: true,
        recommendedAction: "Install certified fire-stopping and provide product documentation",
        includeInReport: true,
      },
      {
        category: "Penetrations",
        description: "Intumescent collars installed on all combustible pipes through fire-rated elements at inter-floor level",
        codeReference: "NCC HP3.7",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Penetrations",
        description: "Electrical conduit penetrations through top and bottom plates sealed",
        codeReference: "NCC DP2",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Cavity Barriers",
        description: "Cavity barriers installed in external wall cavities at each floor level",
        codeReference: "NCC HP3.7",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Cavity Barriers",
        description: "Cavity barriers at the junction of external wall cavities and the floor/ceiling",
        codeReference: "NCC HP3.7",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Documentation",
        description: "Product documentation (ABCB CodeMark or AWA) for fire-rated construction systems available on site",
        codeReference: "NCC HP3.7",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Occupancy Inspection",
    inspectionType: "occupancy",
    folder: "Dwelling 2 Storey (Class 1)",
    description: "Pre-occupancy inspection for two-storey dwelling — NCC Housing Provisions HP4 / EP2.2",
    sortOrder: 6,
    items: [
      {
        category: "Structure",
        description: "All structural elements at both levels complete and consistent with approved drawings",
        codeReference: "NCC HP",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Structure",
        description: "Upper floor structural engineer's sign-off certificate received (where required)",
        codeReference: "NCC HP3.4",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Roof & Walls",
        description: "Roof covering complete, weather-tight and all penetrations flashed",
        codeReference: "NCC HP3.3",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Openings",
        description: "All external doors, windows and glazing at both levels installed and weather-stripped",
        codeReference: "NCC HP3.3",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Stairs & Balustrades",
        description: "Stair riser and going dimensions, handrails and balustrading comply with HP3.9.2",
        codeReference: "NCC HP3.9.2",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Stairs & Balustrades",
        description: "Upper level balcony and void balustrades at correct height and infill spacing",
        codeReference: "NCC HP3.9.2",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Smoke Alarms",
        description: "Smoke alarms installed on every level and in each bedroom zone per EP2.2",
        codeReference: "NCC EP2.2",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        recommendedAction: "Install alarms on both levels in all required positions",
        includeInReport: true,
      },
      {
        category: "Smoke Alarms",
        description: "Alarms interconnected and hardwired, or 10-year lithium battery type as required",
        codeReference: "NCC EP2.2 / AS 3786",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Services",
        description: "Plumbing rough-in complete and hydraulic pressure test passed",
        codeReference: "AS/NZS 3500",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Final Inspection",
    inspectionType: "final",
    folder: "Dwelling 2 Storey (Class 1)",
    description: "Final inspection for occupation certificate — two-storey dwelling — NCC Housing Provisions",
    sortOrder: 7,
    items: [
      {
        category: "Compliance",
        description: "All staged inspection approvals received and documented on file",
        codeReference: "NCC HP",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Site",
        description: "Site drainage, surface water management and subsoil drainage compliant",
        codeReference: "NCC HP2.1",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Compliance",
        description: "Building complete in accordance with all approved plans and specifications",
        codeReference: "NCC HP",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Safety Glazing",
        description: "Safety glazing installed in all hazardous locations at both levels per FP7.4",
        codeReference: "NCC FP7.4 / AS 1288",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Balustrades",
        description: "All balustrades at both levels — height min 1000 mm, infill spacings compliant with HP3.9.2",
        codeReference: "NCC HP3.9.2",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Smoke Alarms",
        description: "All smoke alarms on both levels tested and operational",
        codeReference: "NCC EP2.2",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Energy",
        description: "Energy efficiency compliance documentation provided (NatHERS certificate or DtS path)",
        codeReference: "NCC HP6",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Termite",
        description: "Termite management system documentation and product warranty provided to owner",
        codeReference: "NCC HP4.5",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Certification",
        description: "All required certificates and authorities' sign-offs received",
        codeReference: null,
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Certification",
        description: "Owner provided with maintenance manual or as-built documentation",
        codeReference: null,
        riskLevel: "low",
        isRequired: false,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// Shed Timber Framed (Class 10) — NCC Housing Provisions
// ---------------------------------------------------------------------------

const SHED_TIMBER: BSTemplate[] = [
  {
    name: "Footing Inspection",
    inspectionType: "footing",
    folder: "Shed Timber Framed (Class 10)",
    description: "Footing inspection for timber-framed shed prior to pour — NCC Housing Provisions HP2.2",
    sortOrder: 1,
    items: [
      {
        category: "Excavation",
        description: "Post footing pad or strip footing dimensions per structural drawings",
        codeReference: "NCC HP2.2",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Excavation",
        description: "Natural ground confirmed — footing depth adequate for soil conditions",
        codeReference: "NCC HP2.2",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Reinforcement",
        description: "Reinforcement installed per engineer's or standard detail drawings",
        codeReference: "AS 3600",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Layout",
        description: "Setback from property boundaries, easements and services confirmed",
        codeReference: null,
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Pre-Pour",
        description: "Formwork correctly positioned for column or post base locations",
        codeReference: "NCC HP2.2",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Pre-Pour",
        description: "Excavation clean and free from water, loose material and debris prior to pour",
        codeReference: null,
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Slab Inspection",
    inspectionType: "slab",
    folder: "Shed Timber Framed (Class 10)",
    description: "Slab inspection for timber-framed shed — NCC Housing Provisions HP3.2",
    sortOrder: 2,
    items: [
      {
        category: "Subbase",
        description: "Slab thickness per approved drawings (typically 85–100 mm for Class 10 shed)",
        codeReference: "NCC HP3.2",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Subbase",
        description: "Moisture barrier installed under slab",
        codeReference: "NCC HP3.2",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Reinforcement",
        description: "Mesh reinforcement laid with correct cover and chairs",
        codeReference: "AS 3600",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Services",
        description: "Service conduit and floor penetrations sleeved and correctly positioned",
        codeReference: null,
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Pre-Pour",
        description: "Slab level and falls checked — edge form set correctly",
        codeReference: null,
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Pre-Pour",
        description: "Concrete mix design appropriate for exposure classification",
        codeReference: "AS 1379",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Frame Inspection",
    inspectionType: "frame",
    folder: "Shed Timber Framed (Class 10)",
    description: "Timber frame inspection — NCC Housing Provisions HP3.4 / AS 1684",
    sortOrder: 3,
    items: [
      {
        category: "Framing",
        description: "Timber size and stress grade per AS 1684 or structural specification",
        codeReference: "NCC HP3.4 / AS 1684",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Framing",
        description: "Post, beam and rafter sizes verified against approved drawings",
        codeReference: "AS 1684",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Connections",
        description: "Connection details (bolts, nail plates, straps, joist hangers) per structural drawings",
        codeReference: "AS 1684",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Bracing",
        description: "Roof and wall bracing installed per bracing schedule",
        codeReference: "NCC HP3.4.4",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Cladding Support",
        description: "Purlins at correct spacing for roof cladding type and span",
        codeReference: "AS 1684",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Cladding Support",
        description: "Wall framing or sheeting rails at correct centres for wall cladding",
        codeReference: "AS 1684",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "General",
        description: "Frame is plumb, square and true — excessive twist or bow in members noted",
        codeReference: null,
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Waterproofing Inspection",
    inspectionType: "waterproofing",
    folder: "Shed Timber Framed (Class 10)",
    description: "Roof and wall weatherproofing inspection — NCC Housing Provisions HP3.3",
    sortOrder: 4,
    items: [
      {
        category: "Roof",
        description: "Ridge capping correctly lapped, fixed and sealed",
        codeReference: "NCC HP3.3",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Roof",
        description: "Valley flashings (where applicable) installed and correctly lapped",
        codeReference: "NCC HP3.3",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Roof",
        description: "Sarking installed under roof cladding per HP3.3.1",
        codeReference: "NCC HP3.3.1",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Drainage",
        description: "Gutter and downpipe system sized for roof catchment area",
        codeReference: "AS/NZS 3500.3",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "External Walls",
        description: "Base of walls flashed or sealed to prevent driving rain ingress",
        codeReference: "NCC HP3.3",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Final Inspection",
    inspectionType: "final",
    folder: "Shed Timber Framed (Class 10)",
    description: "Final inspection — timber-framed Class 10 shed",
    sortOrder: 5,
    items: [
      {
        category: "Compliance",
        description: "Building complete per approved plans and specifications",
        codeReference: "NCC HP",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Cladding",
        description: "Roof cladding and wall cladding fully installed and weather-tight",
        codeReference: "NCC HP3.3",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Penetrations",
        description: "All penetrations (doors, windows, services) sealed and flashed",
        codeReference: "NCC HP3.3",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Site",
        description: "Drainage around building adequate — no ponding adjacent to structure",
        codeReference: "NCC HP2.1",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Classification",
        description: "Class 10a use confirmed — building not used or converted for habitation",
        codeReference: "NCC HP / BCA Class 10a",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Certification",
        description: "All required sign-offs, approvals and documentation received",
        codeReference: null,
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// Shed Steel (Class 10) — NCC Housing Provisions
// ---------------------------------------------------------------------------

const SHED_STEEL: BSTemplate[] = [
  {
    name: "Footing Inspection",
    inspectionType: "footing",
    folder: "Shed Steel (Class 10)",
    description: "Footing inspection for steel-framed shed prior to pour — NCC Housing Provisions HP2.2",
    sortOrder: 1,
    items: [
      {
        category: "Excavation",
        description: "Post footing pad or strip footing dimensions and depths per structural drawings",
        codeReference: "NCC HP2.2",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Excavation",
        description: "Natural ground confirmed — depth adequate for soil bearing conditions",
        codeReference: "NCC HP2.2",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Reinforcement",
        description: "Reinforcement per structural engineer's details — anchor bolts positioned and plumbed",
        codeReference: "AS 3600",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: true,
        defectTrigger: true,
        recommendedAction: "Verify anchor bolt positions against column base plate template before pour",
        includeInReport: true,
      },
      {
        category: "Layout",
        description: "Setback from property boundaries, easements and services confirmed",
        codeReference: null,
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Pre-Pour",
        description: "Anchor bolt positions checked against base plate layout — within tolerance",
        codeReference: "AS 4100",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Pre-Pour",
        description: "Excavation clean and free from water, loose material and debris",
        codeReference: null,
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Slab Inspection",
    inspectionType: "slab",
    folder: "Shed Steel (Class 10)",
    description: "Slab inspection for steel-framed shed — NCC Housing Provisions HP3.2",
    sortOrder: 2,
    items: [
      {
        category: "Subbase",
        description: "Slab thickness per approved drawings — typically 85–100 mm for Class 10",
        codeReference: "NCC HP3.2",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Subbase",
        description: "Moisture barrier installed under slab",
        codeReference: "NCC HP3.2",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Reinforcement",
        description: "Mesh reinforcement with correct cover and chairs",
        codeReference: "AS 3600",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Services",
        description: "Service conduit and floor penetrations sleeved and correctly positioned",
        codeReference: null,
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Pre-Pour",
        description: "Slab level and falls confirmed — edge form correctly set",
        codeReference: null,
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Pre-Pour",
        description: "Concrete mix design appropriate for exposure classification",
        codeReference: "AS 1379",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Steel Frame Inspection",
    inspectionType: "steel_frame",
    folder: "Shed Steel (Class 10)",
    description: "Structural steel frame inspection — AS 4100 / structural engineer's specification",
    sortOrder: 3,
    items: [
      {
        category: "Base Connections",
        description: "Column base plates correctly positioned, levelled and anchor bolts torqued to specification",
        codeReference: "AS 4100",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: true,
        defectTrigger: true,
        recommendedAction: "Verify torque values with engineer and document as-built positions",
        includeInReport: true,
      },
      {
        category: "Steel Members",
        description: "Column section sizes and steel grade comply with structural drawings",
        codeReference: "AS 4100",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Connections",
        description: "Rafter and purlin connections bolted correctly — bolt sizes and patterns per connection schedule",
        codeReference: "AS 4100",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Connections",
        description: "All bolts torqued to specification — no missing or under-torqued fasteners",
        codeReference: "AS 4100",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Cladding Support",
        description: "Roof and wall purlins and girts at correct spacing per structural drawings",
        codeReference: "AS 4100",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Bracing",
        description: "Roof and wall bracing rods or cables installed and correctly tensioned",
        codeReference: "AS 4100",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Welds",
        description: "All field welds visually inspected — no cracks, voids or obvious defects",
        codeReference: "AS/NZS 1554",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        recommendedAction: "Engage qualified weld inspector if defects observed",
        includeInReport: true,
      },
      {
        category: "Protection",
        description: "Steel coating or galvanising system complete and appropriate for exposure classification",
        codeReference: "AS 4312",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Waterproofing Inspection",
    inspectionType: "waterproofing",
    folder: "Shed Steel (Class 10)",
    description: "Roof and wall weatherproofing for steel shed — NCC Housing Provisions HP3.3",
    sortOrder: 4,
    items: [
      {
        category: "Roof",
        description: "Ridge cap flashing installed, correctly lapped and sealed",
        codeReference: "NCC HP3.3",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Roof",
        description: "Roof sheet end laps and side laps comply with manufacturer's specification",
        codeReference: "NCC HP3.3",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Drainage",
        description: "Gutter and downpipe system installed and connected to stormwater",
        codeReference: "AS/NZS 3500.3",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Wall Flashings",
        description: "Wall sheeting base flashings correctly installed to exclude water ingress",
        codeReference: "NCC HP3.3",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Penetrations",
        description: "All penetrations (doors, windows, services) sealed and flashed",
        codeReference: "NCC HP3.3",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Final Inspection",
    inspectionType: "final",
    folder: "Shed Steel (Class 10)",
    description: "Final inspection — steel-framed Class 10 shed",
    sortOrder: 5,
    items: [
      {
        category: "Compliance",
        description: "Steel building complete per approved plans and specifications",
        codeReference: "NCC HP / AS 4100",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Structure",
        description: "All structural connections as per engineer's specification — final structural sign-off received",
        codeReference: "AS 4100",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Cladding",
        description: "Roof and wall cladding complete, weather-tight and all penetrations sealed",
        codeReference: "NCC HP3.3",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Site",
        description: "Drainage around building adequate — no ponding adjacent to structure",
        codeReference: "NCC HP2.1",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Classification",
        description: "Class 10a use confirmed — building not used or converted for habitation",
        codeReference: "NCC HP / BCA Class 10a",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Certification",
        description: "All required sign-offs, approvals and documentation received",
        codeReference: null,
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// Class 2-9 — NCC Volume 1
// ---------------------------------------------------------------------------

const CLASS_2_9: BSTemplate[] = [
  {
    name: "Footing Inspection",
    inspectionType: "footing",
    folder: "Class 2-9",
    description: "Footing inspection for Class 2–9 buildings — NCC Volume 1 / AS 3600",
    sortOrder: 1,
    items: [
      {
        category: "Excavation",
        description: "Footing dimensions, type and depth per structural engineer's drawings",
        codeReference: "NCC Vol 1 / AS 3600",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: true,
        defectTrigger: true,
        recommendedAction: "Excavate to required dimensions and confirm with engineer before pour",
        includeInReport: true,
      },
      {
        category: "Excavation",
        description: "Soil bearing capacity confirmed against geotechnical report — no unexpected conditions",
        codeReference: "AS 2870",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        recommendedAction: "Notify structural engineer immediately if soil conditions deviate from report",
        includeInReport: true,
      },
      {
        category: "Reinforcement",
        description: "Reinforcement cover, bar size and spacing per AS 3600 structural drawings",
        codeReference: "AS 3600",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: true,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Reinforcement",
        description: "Concrete mix design appropriate for exposure classification per AS 3600 Table 4.3.2",
        codeReference: "AS 3600 Table 4.3.2",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Layout",
        description: "Setback from property boundaries, services and easements confirmed",
        codeReference: null,
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Pre-Pour",
        description: "Formwork structurally adequate and correctly aligned per drawings",
        codeReference: "AS 3610",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Pre-Pour",
        description: "Excavation dewatered and free from loose material prior to pour",
        codeReference: null,
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Piling",
        description: "Piling or special footing elements inspected per engineer's design — if applicable",
        codeReference: "AS 2159",
        riskLevel: "critical",
        isRequired: false,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Slab Inspection",
    inspectionType: "slab",
    folder: "Class 2-9",
    description: "Slab inspection for Class 2–9 buildings — NCC Volume 1 / AS 3600",
    sortOrder: 2,
    items: [
      {
        category: "Structure",
        description: "Slab thickness per structural drawings — post-tensioned or reinforced as specified",
        codeReference: "AS 3600",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Structure",
        description: "Concrete mix design and post-tension cables or tendons per structural specification",
        codeReference: "AS 3600 / AS/NZS 4672",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Reinforcement",
        description: "Reinforcement or PT cables in correct position with adequate cover and supports",
        codeReference: "AS 3600",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: true,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Structure",
        description: "Edge thickening and construction joint locations approved by engineer",
        codeReference: "AS 3600",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Services",
        description: "Service penetrations sleeved and sign-off obtained from structural engineer",
        codeReference: "AS 3600",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Subbase",
        description: "Damp-proof membrane installed under slab-on-ground",
        codeReference: "NCC Vol 1",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Pre-Pour",
        description: "Slab surface level and flatness tolerances confirmed with surveyor or engineer",
        codeReference: "AS 3610",
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Suspended Slab",
        description: "Formwork and propping for suspended slab adequate and documented — if applicable",
        codeReference: "AS 3610",
        riskLevel: "critical",
        isRequired: false,
        requirePhoto: false,
        defectTrigger: true,
        recommendedAction: "Do not pour suspended slab until propping adequacy confirmed by engineer",
        includeInReport: true,
      },
    ],
  },
  {
    name: "Frame Inspection",
    inspectionType: "frame",
    folder: "Class 2-9",
    description: "Structural frame inspection for Class 2–9 buildings — NCC Volume 1",
    sortOrder: 3,
    items: [
      {
        category: "Structural Members",
        description: "Structural members (concrete, steel, LVL) comply with approved drawings and specification",
        codeReference: "NCC Vol 1 / AS 3600 / AS 4100",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Connections",
        description: "Connection details — bolts, welds, anchorage per engineer's connection schedule",
        codeReference: "AS 4100 / AS 3600",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: true,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Load Path",
        description: "Load path continuity verified between levels — columns, walls and cores aligned",
        codeReference: "NCC Vol 1",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Lateral Resistance",
        description: "Bracing and lateral load resisting system installed (shear walls, cores, diagonal bracing)",
        codeReference: "NCC Vol 1 / AS 1170",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Precast / Tilt-Up",
        description: "Precast or tilt-up panel connections inspected per engineer's shop drawings — if applicable",
        codeReference: "AS 3850",
        riskLevel: "critical",
        isRequired: false,
        requirePhoto: true,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Propping",
        description: "Temporary propping for suspended slabs or precast panels adequate and documented",
        codeReference: "AS 3610",
        riskLevel: "critical",
        isRequired: false,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Alignment",
        description: "Frame dimensions, plumb and alignment within specified tolerances",
        codeReference: "AS 3600 / AS 4100",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Inter-Floor",
        description: "Inter-floor structural connections (beams, columns, corbels) per drawings",
        codeReference: "AS 3600 / AS 4100",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Fire Penetration Inspection",
    inspectionType: "fire_penetration",
    folder: "Class 2-9",
    description: "Fire penetration and passive fire protection inspection — NCC Volume 1 Spec C3.15",
    sortOrder: 4,
    items: [
      {
        category: "FRL",
        description: "Fire-resistance levels (FRL) achieved for all required walls, floors and columns",
        codeReference: "NCC Vol 1 Spec C1.1",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        recommendedAction: "Obtain FRL test report for all fire-rated construction systems",
        includeInReport: true,
      },
      {
        category: "Penetrations",
        description: "All penetrations through fire-rated walls and floors fire-stopped per Spec C3.15",
        codeReference: "NCC Vol 1 Spec C3.15",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: true,
        defectTrigger: true,
        recommendedAction: "Install certified fire-stopping system at every penetration and provide documentation",
        includeInReport: true,
      },
      {
        category: "Penetrations",
        description: "Intumescent collars installed on all combustible pipes passing through fire-rated elements",
        codeReference: "NCC Vol 1 Spec C3.15",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Penetrations",
        description: "Cable and conduit penetrations through fire-rated walls sealed with fire-stopping compound",
        codeReference: "NCC Vol 1 Spec C3.15",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Fire Doors",
        description: "Fire doors, frames and hardware installed and certified per AS 1905.1",
        codeReference: "NCC Vol 1 C2.6 / AS 1905.1",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Fire Doors",
        description: "Smoke seals and intumescent strips fitted to all fire doors",
        codeReference: "NCC Vol 1 C2.6",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Cavity Barriers",
        description: "Cavity barriers installed in wall and ceiling cavities per fire engineering report",
        codeReference: "NCC Vol 1 C2.8",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Documentation",
        description: "FRL test reports for all fire-rated construction systems available on site",
        codeReference: "NCC Vol 1",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Documentation",
        description: "Passive fire protection installation documented with installer certificates",
        codeReference: "NCC Vol 1 Spec C3.15",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Occupancy Inspection",
    inspectionType: "occupancy",
    folder: "Class 2-9",
    description: "Pre-occupancy inspection for Class 2–9 buildings — NCC Volume 1",
    sortOrder: 5,
    items: [
      {
        category: "Fire",
        description: "All fire-rated construction elements complete and certified by engineer or certifier",
        codeReference: "NCC Vol 1 Section C",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Egress",
        description: "Exit widths, travel distances and number of exits comply with NCC Volume 1 Section D",
        codeReference: "NCC Vol 1 Section D",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        recommendedAction: "Confirm compliance with travel distance and exit calculations",
        includeInReport: true,
      },
      {
        category: "Accessibility",
        description: "Accessible path of travel in place per NCC Access requirements — Spec D3.6 / AS 1428.1",
        codeReference: "NCC Vol 1 Spec D3.6 / AS 1428.1",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Mechanical",
        description: "Mechanical ventilation and air conditioning installed per NCC Volume 1 Section F",
        codeReference: "NCC Vol 1 Section F",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Fire Detection",
        description: "Fire detection and alarm system installed and commissioned per AS 1670",
        codeReference: "NCC Vol 1 Section E / AS 1670",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Emergency Systems",
        description: "Emergency lighting and exit signage installed and tested per AS 2293 / NCC Section E",
        codeReference: "NCC Vol 1 Section E / AS 2293",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Hydraulics",
        description: "Hydraulic systems pressure tested and certified by licensed plumber",
        codeReference: "AS/NZS 3500",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Lifts",
        description: "Lift compliance certificate provided where applicable",
        codeReference: "AS 1735",
        riskLevel: "high",
        isRequired: false,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
    ],
  },
  {
    name: "Final Inspection",
    inspectionType: "final",
    folder: "Class 2-9",
    description: "Final inspection for Class 2–9 buildings — NCC Volume 1 occupation certificate",
    sortOrder: 6,
    items: [
      {
        category: "Compliance",
        description: "All staged inspection approvals received and documented on file",
        codeReference: "NCC Vol 1",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Compliance",
        description: "Building complete in accordance with all approved plans and specifications",
        codeReference: "NCC Vol 1",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Fire Safety",
        description: "Fire safety schedule drafted, signed and installed at the building",
        codeReference: "NCC Vol 1 Section E",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Fire Safety",
        description: "BCA / fire engineering compliance report received from fire engineer (where required)",
        codeReference: "NCC Vol 1",
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Fire Safety",
        description: "Essential fire safety measures maintenance schedule provided to building owner",
        codeReference: "NCC Vol 1 Section E",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Accessibility",
        description: "Accessible design elements verified per NCC Access requirements",
        codeReference: "NCC Vol 1 Spec D3.6",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Energy",
        description: "Energy efficiency compliance documentation provided — NCC Section J, NatHERS or JV3",
        codeReference: "NCC Vol 1 Section J",
        riskLevel: "high",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
      {
        category: "Authorities",
        description: "All authority approvals and utility connection certifications received",
        codeReference: null,
        riskLevel: "critical",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: true,
        includeInReport: true,
      },
      {
        category: "Handover",
        description: "As-built documentation and maintenance manuals provided to owner or body corporate",
        codeReference: null,
        riskLevel: "medium",
        isRequired: true,
        requirePhoto: false,
        defectTrigger: false,
        includeInReport: true,
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// Combined export
// ---------------------------------------------------------------------------

const BS_TEMPLATES: BSTemplate[] = [
  ...DWELLING_1_STOREY,
  ...DWELLING_2_STOREY,
  ...SHED_TIMBER,
  ...SHED_STEEL,
  ...CLASS_2_9,
];

// Folders that are no longer part of the new template structure —
// will be cleaned up during the seed run if they have no active inspection results.
const LEGACY_FOLDERS = [
  "Class 10a",
  "Class 10b",
  "Class 1a",
  "Class 1b",
  "Class 2",
  "Class 3",
  "Class 5",
  "Class 6",
  "Class 7a",
];

export async function seedBuildingSurveyorTemplates(): Promise<void> {
  console.log("\n--- Building Surveyor Templates (upsert) ---");

  const { eq, and, gt, inArray } = await import("drizzle-orm");
  const { checklistResultsTable } = await import("../schema/checklists");

  // ------------------------------------------------------------------
  // 0. Clean up legacy folders that no longer exist in the template list
  // ------------------------------------------------------------------
  for (const legacyFolder of LEGACY_FOLDERS) {
    const legacyTemplates = await db
      .select({ id: checklistTemplatesTable.id })
      .from(checklistTemplatesTable)
      .where(eq(checklistTemplatesTable.folder, legacyFolder));

    for (const legacyTmpl of legacyTemplates) {
      const legacyItems = await db
        .select({ id: checklistItemsTable.id })
        .from(checklistItemsTable)
        .where(eq(checklistItemsTable.templateId, legacyTmpl.id));

      if (legacyItems.length === 0) {
        await db.delete(checklistTemplatesTable).where(eq(checklistTemplatesTable.id, legacyTmpl.id));
        continue;
      }

      const itemIds = legacyItems.map((i) => i.id);
      const [usedResult] = await db
        .select({ id: checklistResultsTable.id })
        .from(checklistResultsTable)
        .where(inArray(checklistResultsTable.checklistItemId, itemIds))
        .limit(1);

      if (!usedResult) {
        await db.delete(checklistItemsTable).where(eq(checklistItemsTable.templateId, legacyTmpl.id));
        await db.delete(checklistTemplatesTable).where(eq(checklistTemplatesTable.id, legacyTmpl.id));
      }
    }
  }

  // ------------------------------------------------------------------
  // 1. Upsert all current templates
  // ------------------------------------------------------------------
  for (const tmpl of BS_TEMPLATES) {
    const [existing] = await db
      .select({ id: checklistTemplatesTable.id })
      .from(checklistTemplatesTable)
      .where(and(
        eq(checklistTemplatesTable.folder, tmpl.folder),
        eq(checklistTemplatesTable.inspectionType, tmpl.inspectionType),
      ))
      .limit(1);

    let templateId: number;
    if (existing) {
      await db.update(checklistTemplatesTable)
        .set({
          name: tmpl.name,
          discipline: "Building Surveyor",
          folder: tmpl.folder,
          description: tmpl.description,
          sortOrder: tmpl.sortOrder,
          isGlobal: true,
        })
        .where(eq(checklistTemplatesTable.id, existing.id));
      templateId = existing.id;
    } else {
      const [tmplRow] = await db
        .insert(checklistTemplatesTable)
        .values({
          name: tmpl.name,
          discipline: "Building Surveyor",
          inspectionType: tmpl.inspectionType,
          folder: tmpl.folder,
          description: tmpl.description,
          sortOrder: tmpl.sortOrder,
          isGlobal: true,
        })
        .returning();
      templateId = tmplRow.id;
    }

    // 2. Upsert items by orderIndex — update in-place to preserve IDs
    for (const [i, item] of tmpl.items.entries()) {
      const orderIndex = i + 1;
      const itemData = {
        category: item.category,
        description: item.description,
        codeReference: item.codeReference ?? null,
        riskLevel: item.riskLevel,
        isRequired: item.isRequired,
        requirePhoto: item.requirePhoto,
        defectTrigger: item.defectTrigger,
        recommendedAction: item.recommendedAction ?? null,
        includeInReport: item.includeInReport,
      };

      const [existingItem] = await db
        .select({ id: checklistItemsTable.id })
        .from(checklistItemsTable)
        .where(and(
          eq(checklistItemsTable.templateId, templateId),
          eq(checklistItemsTable.orderIndex, orderIndex),
        ))
        .limit(1);

      if (existingItem) {
        await db.update(checklistItemsTable)
          .set(itemData)
          .where(eq(checklistItemsTable.id, existingItem.id));
      } else {
        await db.insert(checklistItemsTable)
          .values({ templateId, orderIndex, ...itemData });
      }
    }

    // 3. Remove extra items only if unused in any inspection
    const extras = await db
      .select({ id: checklistItemsTable.id })
      .from(checklistItemsTable)
      .where(and(
        eq(checklistItemsTable.templateId, templateId),
        gt(checklistItemsTable.orderIndex, tmpl.items.length),
      ));

    for (const extra of extras) {
      const [used] = await db
        .select({ id: checklistResultsTable.id })
        .from(checklistResultsTable)
        .where(eq(checklistResultsTable.checklistItemId, extra.id))
        .limit(1);
      if (!used) {
        await db.delete(checklistItemsTable)
          .where(eq(checklistItemsTable.id, extra.id));
      }
    }

    console.log(`  ✓ [Building Surveyor] ${tmpl.folder} — ${tmpl.name} (${tmpl.items.length} items)`);
  }
}
